Map<String?, String?> day_icon = {
  "Солнечно": "assets/icons/weather/day/113.png",
  "Переменная облачность": "assets/icons/weather/day/116.png",
  "Облачно": "assets/icons/weather/day/119.png",
  "Пасмурно": "assets/icons/weather/day/122.png",
  "Дымка": "assets/icons/weather/day/143.png",
  "Местами дождь": "assets/icons/weather/day/176.png",
  "Местами снег": "assets/icons/weather/day/179.png",
  "Местами дождь со снегом": "assets/icons/weather/day/182.png",
  "Местами замерзающая морось": "assets/icons/weather/day/185.png",
  "Местами грозы": "assets/icons/weather/day/200.png",
  "Поземок": "assets/icons/weather/day/227.png",
  "Метель": "assets/icons/weather/day/230.png",
  "Туман": "assets/icons/weather/day/248.png",
  "Переохлажденный туман": "assets/icons/weather/day/260.png",
  "Местами слабая морось": "assets/icons/weather/day/263.png",
  "Слабая морось": "assets/icons/weather/day/266.png",
  "Замерзающая морось": "assets/icons/weather/day/281.png",
  "Сильная замерзающая морось": "assets/icons/weather/day/284.png",
  "Местами небольшой дождь": "assets/icons/weather/day/293.png",
  "Небольшой дождь": "assets/icons/weather/day/296.png",
  "Временами умеренный дождь": "assets/icons/weather/day/299.png",
  "Умеренный дождь": "assets/icons/weather/day/302.png",
  "Временами сильный дождь": "assets/icons/weather/day/305.png",
  "Сильный дождь": "assets/icons/weather/day/308.png",
  "Слабый переохлажденный дождь": "assets/icons/weather/day/311.png",
  "Умеренный или сильный переохлажденный дождь":
      "assets/icons/weather/day/314.png",
  "Небольшой дождь со снегом": "assets/icons/weather/day/317.png",
  "Умеренный или сильный дождь со снегом": "assets/icons/weather/day/320.png",
  "Местами небольшой снег": "assets/icons/weather/day/323.png",
  "Небольшой снег": "assets/icons/weather/day/326.png",
  "Местами умеренный снег": "assets/icons/weather/day/329.png",
  "Умеренный снег": "assets/icons/weather/day/332.png",
  "Местами сильный снег": "assets/icons/weather/day/335.png",
  "Сильный снег": "assets/icons/weather/day/338.png",
  "Ледяной дождь": "assets/icons/weather/day/350.png",
  "Небольшой ливневый дождь": "assets/icons/weather/day/353.png",
  "Умеренный или сильный ливневый дождь": "assets/icons/weather/day/356.png",
  "Сильные ливни": "assets/icons/weather/day/359.png",
  "Небольшой ливневый дождь со снегом": "assets/icons/weather/day/362.png",
  "Умеренные или сильные ливневые дожди со снегом":
      "assets/icons/weather/day/365.png",
  "Умеренный или сильный снег": "assets/icons/weather/day/371.png",
  "Небольшой ледяной дождь": "assets/icons/weather/day/374.png",
  "Умеренный или сильный ледяной дождь": "assets/icons/weather/day/377.png",
  "В отдельных районах местами небольшой дождь с грозой":
      "assets/icons/weather/day/386.png",
  "В отдельных районах умеренный или сильный дождь с грозой":
      "assets/icons/weather/day/389.png",
  "В отдельных районах местами небольшой снег с грозой":
      "assets/icons/weather/day/392.png",
  "В отдельных районах умеренный или сильный снег с грозой":
      "assets/icons/weather/day/395.png",
};

Map<String?, String?> night_icon = {
  "Ясно": "assets/icons/weather/night/113.png",
  "Переменная облачность": "assets/icons/weather/night/116.png",
  "Облачно": "assets/icons/weather/night/119.png",
  "Пасмурно": "assets/icons/weather/night/122.png",
  "Дымка": "assets/icons/weather/night/143.png",
  "Местами дождь": "assets/icons/weather/night/176.png",
  "Местами снег": "assets/icons/weather/night/179.png",
  "Местами дождь со снегом": "assets/icons/weather/night/182.png",
  "Местами замерзающая морось": "assets/icons/weather/night/185.png",
  "Местами грозы": "assets/icons/weather/night/200.png",
  "Поземок": "assets/icons/weather/night/227.png",
  "Метель": "assets/icons/weather/night/230.png",
  "Туман": "assets/icons/weather/night/248.png",
  "Переохлажденный туман": "assets/icons/weather/night/260.png",
  "Местами слабая морось": "assets/icons/weather/night/263.png",
  "Слабая морось": "assets/icons/weather/night/266.png",
  "Замерзающая морось": "assets/icons/weather/night/281.png",
  "Сильная замерзающая морось": "assets/icons/weather/night/284.png",
  "Местами небольшой дождь": "assets/icons/weather/night/293.png",
  "Небольшой дождь": "assets/icons/weather/night/296.png",
  "Временами умеренный дождь": "assets/icons/weather/night/299.png",
  "Умеренный дождь": "assets/icons/weather/night/302.png",
  "Временами сильный дождь": "assets/icons/weather/night/305.png",
  "Сильный дождь": "assets/icons/weather/night/308.png",
  "Слабый переохлажденный дождь": "assets/icons/weather/night/311.png",
  "Умеренный или сильный переохлажденный дождь":
      "assets/icons/weather/night/314.png",
  "Небольшой дождь со снегом": "assets/icons/weather/night/317.png",
  "Умеренный или сильный дождь со снегом": "assets/icons/weather/night/320.png",
  "Местами небольшой снег": "assets/icons/weather/night/323.png",
  "Небольшой снег": "assets/icons/weather/night/326.png",
  "Местами умеренный снег": "assets/icons/weather/night/329.png",
  "Умеренный снег": "assets/icons/weather/night/332.png",
  "Местами сильный снег": "assets/icons/weather/night/335.png",
  "Сильный снег": "assets/icons/weather/night/338.png",
  "Ледяной дождь": "assets/icons/weather/night/350.png",
  "Небольшой ливневый дождь": "assets/icons/weather/night/353.png",
  "Умеренный или сильный ливневый дождь": "assets/icons/weather/night/356.png",
  "Сильные ливни": "assets/icons/weather/night/359.png",
  "Небольшой ливневый дождь со снегом": "assets/icons/weather/night/362.png",
  "Умеренные или сильные ливневые дожди со снегом":
      "assets/icons/weather/night/365.png",
  "Умеренный или сильный снег": "assets/icons/weather/night/371.png",
  "Небольшой ледяной дождь": "assets/icons/weather/night/374.png",
  "Умеренный или сильный ледяной дождь": "assets/icons/weather/night/377.png",
  "В отдельных районах местами небольшой дождь с грозой":
      "assets/icons/weather/night/386.png",
  "В отдельных районах умеренный или сильный дождь с грозой":
      "assets/icons/weather/night/389.png",
  "В отдельных районах местами небольшой снег с грозой":
      "assets/icons/weather/night/392.png",
  "В отдельных районах умеренный или сильный снег с грозой":
      "assets/icons/weather/night/395.png",
};
